language: rust
os: linux
rust: stable
dist: xenial

sudo: true

before_install:
  - rustup component add clippy

script:
  - cargo clippy
  - cargo build --all
  - cargo test --all
  - cargo check --all
  - cargo doc --all --no-deps

cache:
  directories:
    - ~/.cargo
